In [48]:
from utils_peter import data_updater
import re
import json
import pandas as pd
import os

In [29]:
with open('../Facebook/Denmark/Movement_range/Denmark_2020_02_21.csv') as f:
    dat = json.load(f, head)

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

In [51]:
path = '../Facebook/Denmark/Movement_range/'
files = os.listdir(path)

In [56]:
dat = pd.read_csv(path+files[10])
dat

            ds crisis_name  ...  all_day_bing_tiles_visited_relative_change all_day_ratio_single_tile_users
0   2020-03-02    DK_NUTS3  ...                                    0.015718                        0.168328
1   2020-03-02    DK_NUTS3  ...                                    0.035932                        0.121529
2   2020-03-02    DK_NUTS3  ...                                    0.038561                        0.121307
3   2020-03-02    DK_NUTS3  ...                                    0.069343                        0.119706
4   2020-03-02    DK_NUTS3  ...                                    0.033410                        0.124927
5   2020-03-02    DK_NUTS3  ...                                    0.043366                        0.124577
6   2020-03-02    DK_NUTS3  ...                                    0.024142                        0.116795
7   2020-03-02    DK_NUTS3  ...                                    0.052164                        0.130699
8   2020-03-02    DK_NUTS3  ...                                    0.042671                        0.134674
9   2020-03-02    DK_NUTS3  ...                                    0.067583                        0.123774
10  2020-03-02    DK_NUTS3  ...                                    0.039564                        0.118347

[11 rows x 10 columns]

            ds crisis_name  ...  all_day_bing_tiles_visited_relative_change all_day_ratio_single_tile_users
0   2020-03-02    DK_NUTS3  ...                                    0.015718                        0.168328
1   2020-03-02    DK_NUTS3  ...                                    0.035932                        0.121529
2   2020-03-02    DK_NUTS3  ...                                    0.038561                        0.121307
3   2020-03-02    DK_NUTS3  ...                                    0.069343                        0.119706
4   2020-03-02    DK_NUTS3  ...                                    0.033410                        0.124927
5   2020-03-02    DK_NUTS3  ...                                    0.043366                        0.124577
6   2020-03-02    DK_NUTS3  ...                                    0.024142                        0.116795
7   2020-03-02    DK_NUTS3  ...                                    0.052164                        0.130699
8   2020-03-02    DK_NUTS3  ...                                    0.042671                        0.134674
9   2020-03-02    DK_NUTS3  ...                                    0.067583                        0.123774
10  2020-03-02    DK_NUTS3  ...                                    0.039564                        0.118347

[11 rows x 10 columns]

In [60]:
path = '../Facebook/Sweden/population_tile/'
files = os.listdir(path)
pd.read_csv(path+files[0]).columns

Index(['lat', 'lon', 'quadkey', 'country', 'date_time', 'n_baseline',
       'n_crisis', 'n_difference', 'density_baseline', 'density_crisis',
       'percent_change', 'clipped_z_score', 'ds'],
      dtype='object')